---
sudo: false
language: go
go:
  - 1.12.x
os:
  - linux
matrix:
  fast_finish: true
script:
  - make vendor && ./hack/tree_status.sh
  - make lint
  - go run example/main.go
  - go run example/main.go -h
